'use client';

import { motion } from 'framer-motion';
import { Check, Copy, Loader2, QrCode, ShieldCheck } from 'lucide-react';
import { TotpData } from '../types';

type TotpSetupFlowProps = {
  totpData: TotpData;
  verifyCode: string;
  actionLoading: boolean;
  copiedKey: string | null;
  onCopy: (key: string, value: string) => void;
  onVerifyCodeChange: (value: string) => void;
  onVerifyAndEnable: () => void;
  onCancel: () => void;
};

export function TotpSetupFlow({
  totpData,
  verifyCode,
  actionLoading,
  copiedKey,
  onCopy,
  onVerifyCodeChange,
  onVerifyAndEnable,
  onCancel,
}: TotpSetupFlowProps) {
  const manualKeyCopied = copiedKey === 'manual-entry-key';

  return (
    <motion.section
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="lg:col-span-4"
    >
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h3 className="text-xl font-semibold">Setup Authenticator</h3>
          <p className="text-foreground-muted mt-1 max-w-2xl">
            Scan the QR code, save the manual key if needed, then enter the 6-digit code from
            your authenticator app.
          </p>
        </div>

        <div className="inline-flex w-fit items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
          <ShieldCheck className="h-4 w-4" />
          Two-step setup
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-4">
        <article className="card lg:col-span-2">
          <div className="mb-5 flex items-start gap-3">
            <div className="rounded-xl bg-primary/10 p-3 text-primary">
              <QrCode className="h-5 w-5" />
            </div>
            <div>
              <p className="font-semibold text-foreground">Step 1: Scan QR Code</p>
              <p className="mt-1 text-sm text-foreground-muted">
                Use Google Authenticator, Authy, Microsoft Authenticator, or any compatible TOTP app.
              </p>
            </div>
          </div>

          <div className="flex justify-center">
            <div className="rounded-xl bg-white p-4 shadow-sm">
              <img src={totpData.qrCode} alt="Authenticator QR Code" className="h-52 w-52" />
            </div>
          </div>
        </article>

        <article className="card lg:col-span-2">
          <div className="mb-5">
            <p className="font-semibold text-foreground">Manual Setup Key</p>
            <p className="mt-1 text-sm text-foreground-muted">
              If you cannot scan the QR code, copy this key into your authenticator app manually.
            </p>
          </div>

          <div className="flex flex-col gap-2 sm:flex-row sm:items-stretch">
            <code className="flex-1 rounded-lg bg-background-elevated p-3 font-mono text-sm break-all">
              {totpData.manualEntryKey}
            </code>

            <button
              type="button"
              onClick={() => onCopy('manual-entry-key', totpData.manualEntryKey)}
              title={manualKeyCopied ? 'Copied' : 'Copy'}
              className={`btn-secondary flex h-11 items-center justify-center gap-2 px-4 text-sm transition active:scale-95 ${
                manualKeyCopied ? 'border-accent-green/30 bg-accent-green/10 text-accent-green' : ''
              }`}
            >
              {manualKeyCopied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {manualKeyCopied ? 'Copied' : 'Copy'}
            </button>
          </div>
        </article>

        <article className="card lg:col-span-4">
          <div className="grid gap-4 lg:grid-cols-4 lg:items-end">
            <div className="lg:col-span-2">
              <p className="font-semibold text-foreground">Step 2: Enter Verification Code</p>
              <p className="mt-1 text-sm text-foreground-muted">
                Enter the 6-digit code generated by your authenticator app.
              </p>
            </div>

            <div className="lg:col-span-1">
              <label htmlFor="two-factor-verification-code" className="sr-only">
                Two-factor verification code
              </label>
              <input
                id="two-factor-verification-code"
                name="verificationCode"
                aria-label="Two-factor verification code"
                type="text"
                value={verifyCode}
                onChange={(event) =>
                  onVerifyCodeChange(event.target.value.replace(/\D/g, '').slice(0, 6))
                }
                className="input h-11 w-full text-center font-mono text-2xl tracking-widest"
                placeholder="000000"
                maxLength={6}
              />
            </div>

            <div className="flex flex-col gap-2 sm:flex-row lg:col-span-1 lg:justify-end">
              <button
                type="button"
                onClick={onVerifyAndEnable}
                disabled={verifyCode.length !== 6 || actionLoading}
                className="btn-primary h-11 w-full px-6 lg:w-auto"
              >
                {actionLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : 'Verify & Enable'}
              </button>

              <button
                type="button"
                onClick={onCancel}
                className="btn-secondary h-11 w-full px-6 lg:w-auto"
              >
                Cancel
              </button>
            </div>
          </div>
        </article>
      </div>
    </motion.section>
  );
}
